### ISSUE TITLE
Issue while compiling

### ISSUE THREAD

**Issue by prathamk22** [ChimeraFlutter/Chimera-Flutter-Code-Push#1]
```
Unhandled exception:
DioError [DioErrorType.other]: SocketException: Failed host lookup: 'chimera-code.com' (OS Error: nodename nor servname provided, or not known, errno = 8)
#0      DioMixin.assureDioError (package:dio/src/dio_mixin.dart:819)
#1      DioMixin._dispatchRequest (package:dio/src/dio_mixin.dart:678)
<asynchronous suspension>
#2      DioMixin.fetch.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:586)
<asynchronous suspension>

#0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:618)
#1      _RootZone.runBinary (dart:async/zone.dart:1690)
#2      _FutureListener.handleError (dart:async/future_impl.dart:174)
#3      Future._propagateToListeners.handleError (dart:async/future_impl.dart:778)
#4      Future._propagateToListeners (dart:async/future_impl.dart:799)
#5      Future._completeError (dart:async/future_impl.dart:609)
#6      _SyncCompleter._completeError (dart:async/future_impl.dart:60)
#7      _Completer.completeError (dart:async/future_impl.dart:32)
#8      Future.any.onError (dart:async/future.dart:544)
#9      _RootZone.runBinary (dart:async/zone.dart:1690)
#10     _FutureListener.handleError (dart:async/future_impl.dart:174)
#11     Future._propagateToListeners.handleError (dart:async/future_impl.dart:778)
#12     Future._propagateToListeners (dart:async/future_impl.dart:799)
#13     Future._completeError (dart:async/future_impl.dart:609)
#14     Future._chainForeignFuture.<anonymous closure> (dart:async/future_impl.dart:554)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193)
```

Getting this error while compiling the code using rust_compiler 1.0.7.

**Comment by yrjwcharm** [comment]
![image](https://user-images.githubusercontent.com/34397383/177030899-41bacefc-c43e-44a2-b1f2-82b2bc9f498f.png)

**Comment by huongrealest** [comment]
I m having this issue too

**Comment by yrjwcharm** [comment]
It is not recommended to use this library, there are too many hot update pits,

**Comment by Aaron009** [comment]
The workload of the hot update is too large, and it is impossible to allocate manpower.
